# Generated by Django 3.2.18 on 2023-05-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название ингридиента')),
                ('quantity', models.IntegerField()),
                ('measurement', models.CharField(max_length=20, verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название блюда', max_length=200, verbose_name='Название рецепта')),
                ('image', models.ImageField(upload_to='recipe/', verbose_name='Картинка')),
                ('description', models.TextField(help_text='Добавьте описание рецепта', max_length=1000, verbose_name='Описание рецепта')),
                ('time', models.IntegerField(verbose_name='Время приготовления')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('color', models.TextField(unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
