# Generated by Django 3.2.18 on 2023-05-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingridients',
            old_name='measurement',
            new_name='measurement_unit',
        ),
        migrations.RemoveField(
            model_name='ingridients',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.TextField(choices=[('#fecc4d', '#fecc4d'), ('#48a3e7', '#48a3e7'), ('#ef3a3a', '#ef3a3a')], unique=True),
        ),
    ]
