# Generated by Django 3.2.18 on 2023-06-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_rename_ingredients_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipe.RecipeIngredients', to='recipe.Ingredient', verbose_name='Ингридиенты'),
        ),
    ]
