# Generated by Django 3.2.18 on 2023-06-10 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredients',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_recipe', to='recipe.ingredient', unique=True, verbose_name='Ингридиент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredient', to='recipe.recipe', unique=True, verbose_name='Рецепт'),
        ),
    ]
