# Generated by Django 3.2.18 on 2023-06-10 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_auto_20230610_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
