# Generated by Django 3.2.18 on 2023-06-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_rename_ingredients_recipe_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
