# Generated by Django 3.2.18 on 2023-06-10 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_auto_20230610_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
